apiVersion: v1
kind: ConfigMap
metadata:
  name: example
  namespace: example
  annotations:
    kform.dev/block-type: input
    kform.dev/resource-id: context ## this serves as a way to add default and manage the merge 
    kform.dev/default: "true"
data: 
  clusterName: example
  revision: v1