apiVersion: claim.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: '["workloadcluster", input.context[0].data.clusterName, count.index].concat("-")'
  namespace: input.context[0].metadata.namespace
  annotations:
    "kform.dev/count": input.context[0].data.count
spec:
  clusterName: "[input.context[0].data.clusterName, 'workloadCluster'].concat('-')"
  revision: input.context[0].data.revision
  something: x
  number: count.index

