apiVersion: v1
kind: ConfigMap
metadata:
  name: edge01
  namespace: default
  annotations:
    kform.dev/block-type: data
    kform.dev/resource-type: kubernetes_manifest 
    kform.dev/resource-id: edge01 
